export const allGames = [
  { name: "CarPuzzle", num_players: "1 player" },
  { name: "Chess", num_players: "2 players" },
  { name: "ConnectFour", num_players: "2 players" },
  { name: "Crosswords", num_players: "1 player" },
  { name: "FifteenPuzzle", num_players: "1 player" },
  { name: "GuessTheNumber", num_players: "1 player" },
  { name: "GuessWho", num_players: "1 player" },
  { name: "Hangman", num_players: "1 player" },
  { name: "LogicPuzzle", num_players: "1 player" },
  { name: "MathProof", num_players: "1 player" },
  { name: "Minesweeper", num_players: "1 player" },
  { name: "Sudoku", num_players: "1 player" },
  { name: "TowerOfHanoi", num_players: "1 player" },
  { name: "TwentyQuestions", num_players: "1 player" },
  { name: "WordLadder", num_players: "1 player" },
  { name: "WordSearch", num_players: "1 player" },
  { name: "Battleship", num_players: "2 players" },
  { name: "Brass", num_players: "2 to 4 players" },
  { name: "Debate", num_players: "2 players" },
  { name: "DontSayIt", num_players: "2 players" },
  { name: "IteratedPrisonersDilemma", num_players: "2 players" },
  { name: "Jaipur", num_players: "2 players" },
  { name: "LetterAuction", num_players: "2 players" },
  { name: "LiarsDice", num_players: "2 players" },
  { name: "Mastermind", num_players: "1 player" },
  { name: "MemoryGame", num_players: "2 players" },
  { name: "Negotiation", num_players: "2 players" },
  { name: "Poker", num_players: "2 to 10 players" },
  { name: "ScenarioPlanning", num_players: "2 players" },
  { name: "SpellingBee", num_players: "2 players" },
  { name: "SpiteAndMalice", num_players: "2 players" },
  { name: "Stratego", num_players: "2 players" },
  { name: "Taboo", num_players: "4 or more players" },
  { name: "Tak", num_players: "2 players" },
  { name: "UltimateTicTacToe", num_players: "2 players" },
  { name: "TruthAndDeception", num_players: "2 players" },
  { name: "WordChains", num_players: "2 players" },
  { name: "7 Wonders", num_players: "2 to 7 players" },
  { name: "Bohnanza", num_players: "2 to 7 players" },
  { name: "Codenames", num_players: "4 or more players" },
  { name: "Diplomacy", num_players: "7 players" },
  { name: "Risk", num_players: "2 to 6 players" },
  { name: "SettlersOfCatan", num_players: "3 to 4 players" },
  { name: "TerraformingMars", num_players: "1 to 5 players" },
  { name: "Werewolf", num_players: "6 or more players" }
]